name: Build Release Packages
on:
  push:
    tags: 'v*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Dist Packages
        run: make dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Slim Release
        id: upload-slim
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.Slim.zip
          asset_name: GuideMe.Slim.zip
          asset_content_type: application/zip
      - name: Upload 32-bit Release
        id: upload-32-bit
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.32-bit.zip
          asset_name: GuideMe.32-bit.zip
          asset_content_type: application/zip
      - name: Upload 64-bit Release
        id: upload-64-bit
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/artifacts/GuideMe.64-bit.zip
          asset_name: GuideMe.64-bit.zip
          asset_content_type: application/zip